spring:
  application:
    name: love-ai-agent
  profiles:
    active: local
  ai:
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
    #        stdio:
    #          servers-configuration: classpath:mcp-servers.json
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cbltps.loveaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
#knife4j:
#  enable: true
#  openapi:
#    title: "接口文档"
#    version: 1.0
#    group:
#      default:
#        api-rule: package
#        api-rule-res.   ources:
#          - com.cbiltps.loveaiagent.controller
# searchAPI
search-api:
  api-key: 你的 API Key
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG
